# -*- coding: utf-8 -*-

import os
import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter
from scipy.signal import savgol_filter


def load_data(filename, smooth=False, filter_window=3, order=1):
    """
    Reads the input datafile which is a multiindex pandas array generated by DeepLabCut as a result of analyzing a video.

    Parameters
    ----------
    filename: string
        Full path of the multiindex pandas array(.h5) file as a string.

    smooth: Bool
        Optional. Smooths coordinates of all bodyparts in the dataframe.

    filter_window: int
        Optional. Only used if the optional argument `smooth` is set to True. The length of filter window which needs to be a positive odd integer
    order: int
        Optional. Only used if the optional argument `smooth` is set to True. Order of the polynomial to fit the data. The order must be less than the filter_window

    Outputs
    -------
    df: dataframe; smoothed in case the optional argument `smooth` is set to True.
    bodyparts: List of unique bodyparts in the dataframe.
    scorer: Scorer name as string.

    Example
    -------
    Linux/MacOS
    >>> df,bodyparts,scorer = dlc2kinematics.load_data('/home/data/video.h5')
    Windows
    >>> df,bodyparts,scorer = dlc2kinematics.load_data('C:\\yourusername\\rig-95\\video.h5')

    """
    try:
        df = pd.read_hdf(filename, "df_with_missing")
    except KeyError:
        df = pd.read_hdf(filename)
    bodyparts = df.columns.get_level_values("bodyparts").unique().to_list()
    scorer = df.columns.get_level_values(0)[0]
    if smooth:
        df = smooth_trajectory(
            df,
            bodyparts,
            filter_window,
            order,
            deriv=0,
            save=False,
            output_filename=None,
            destfolder=None,
        )

    return df, bodyparts, scorer

def smooth_trajectory(
    df,
    bodyparts,
    filter_window=3,
    order=1,
    deriv=0,
    save=False,
    output_filename=None,
    destfolder=None,
):
    """
    Smooths the input data which is a multiindex pandas array generated by DeepLabCut as a result of analyzing a video.

    Parameters
    ----------
    df: Pandas multiindex dataframe

    bodyparts: List
        List of bodyparts to smooth. To smooth all the bodyparts use bodyparts=['all']

    filter_window: int
        The length of filter window which needs to be a positive odd integer

    order: int
        Order of the polynomial to fit the data. The order must be less than the filter_window

    deriv: int
        Optional. Computes the derivative. If order=1, it computes the velocity on the smoothed data, if order=2 it computes the acceleration on the smoothed data.

    Outputs
    -------
    df: smoothed dataframe

    Example
    -------
    >>> df_smooth = kinematics.smooth_trajectory(df,bodyparts=['nose','shoulder'],window_length=11,order=3)

    To smooth all the bodyparts in the dataframe, use
    >>> df_smooth = kinematics.smooth_trajectory(df,bodyparts=['all'],window_length=11,order=3)

    """
    df = df.copy()
    xy = df.columns.get_level_values("coords") != "likelihood"
    if bodyparts[0] == "all":
        mask = np.ones(df.shape[1], dtype=bool)
    else:
        mask = df.columns.get_level_values("bodyparts").isin(bodyparts)
    to_smooth = xy & mask
    df.loc[:, to_smooth] = savgol_filter(
        df.loc[:, to_smooth], filter_window, order, deriv, axis=0
    )
    df_cut = df.loc[:, mask]
    if not destfolder:
        destfolder = os.getcwd()
    if not output_filename:
        output_filename = (
            "dataFrame_smooth_" + df.columns.get_level_values("scorer").unique()[0]
        )

    if save:
        print("Saving the smoothed data as a pandas array in %s " % destfolder)
        df_cut.to_hdf(
            os.path.join(destfolder, output_filename + ".h5"),
            "df_with_missing",
            format="table",
            mode="w",
        )
    return df_cut

def extract_corner_points_over_frames(df, scorer, corner_names, bodypart_prefix='single'):
    """
    Extracts the corner points for each frame from the DataFrame.

    Parameters
    ----------
    df : pandas.DataFrame
        The DataFrame containing the tracked data.
    scorer : str
        The name of the scorer used in the DataFrame.
    corner_names : list
        A list of strings representing the names of the corners to be extracted.
    bodypart_prefix : str, optional
        The prefix used to identify the corners in the bodyparts, by default 'single'.

    Returns
    -------
    dict
        A dictionary where each key is a corner name provided in corner_names,
        and its value is a list of (x, y) tuples for each frame.
    """
    corner_points = {corner: [] for corner in corner_names}

    for corner in corner_names:
        x_col = (scorer, bodypart_prefix, corner, 'x')
        y_col = (scorer, bodypart_prefix, corner, 'y')
        for i in range(len(df)):
            x = df[x_col].iloc[i]
            y = df[y_col].iloc[i]
            corner_points[corner].append((x, y))

    return corner_points

def is_inside_rectangle(x, y, min_x, max_x, min_y, max_y):
    """
    Checks if a point is inside the given rectangle defined by min and max x, y coordinates.

    Parameters
    ----------
    x, y : float
        The x and y coordinates of the point to check.
    min_x, max_x, min_y, max_y : float
        The minimum and maximum x and y coordinates defining the rectangle.

    Returns
    -------
    bool
        True if the point is inside the rectangle, False otherwise.
    """
    return min_x <= x <= max_x and min_y <= y <= max_y



def compute_time_inside_dynamic_rectangle_single(df, scorer, ant, corner_names, tracked_keypoint_name, frame_rate=10):
    """
    Computes the time spent by 'ant' inside a dynamically defined rectangle based on corner points over each frame.

    Parameters
    ----------
    df : pandas.DataFrame
        The DataFrame containing the tracked data.
    scorer : str
        The name of the scorer used in the DataFrame.
    frame_rate : int, optional
        The frame rate of the video, by default 30 frames per second (fps).

    Returns
    -------
    float
        The total time in seconds that 'ant' spends inside the rectangle.
    """
    corner_points = extract_corner_points_over_frames(df, scorer,corner_names)
    ant_x_col = (scorer, ant, tracked_keypoint_name, 'x')
    ant_y_col = (scorer, ant, tracked_keypoint_name, 'y')
    inside_count = 0

    for i in range(len(df)):
        min_x = min(corner_points[corner][i][0] for corner in corner_points)
        max_x = max(corner_points[corner][i][0] for corner in corner_points)
        min_y = min(corner_points[corner][i][1] for corner in corner_points)
        max_y = max(corner_points[corner][i][1] for corner in corner_points)

        ant_x = df[ant_x_col].iloc[i]
        ant_y = df[ant_y_col].iloc[i]

        if is_inside_rectangle(ant_x, ant_y, min_x, max_x, min_y, max_y):
            inside_count += 1

    # Compute time spent inside
    time_inside_seconds = inside_count / frame_rate

    return time_inside_seconds

def compute_time_inside_dynamic_rectangle(df, scorer, ants, corner_names, tracked_keypoint_name, frame_rate=10):
    """
    Computes the time spent by multiple ants inside a dynamically defined rectangle based on corner points over each frame.

    Parameters
    ----------
    df : pandas.DataFrame
        The DataFrame containing the tracked data.
    scorer : str
        The name of the scorer used in the DataFrame.
    ants : list
        A list of ant identifiers (e.g., 'ant_1', 'ant_2') to check within the rectangle.
    corner_names : list
        A list of strings representing the names of the corners to be extracted.
    tracked_keypoint_name : str
        The name of the kypoint used fr analysis
    frame_rate : int
        The frame rate of the video, by default 10 frames per second (fps).

    Returns
    -------
    dict
        A dictionary where each key is an ant identifier and its value is the total time in seconds that ant spends inside the rectangle.
    """
    corner_points = extract_corner_points_over_frames(df, scorer, corner_names)
    times_inside = {ant: 0 for ant in ants}  # Initialize a dictionary to hold time inside for each ant

    for i in range(len(df)):
        min_x = min(corner_points[corner][i][0] for corner in corner_points)
        max_x = max(corner_points[corner][i][0] for corner in corner_points)
        min_y = min(corner_points[corner][i][1] for corner in corner_points)
        max_y = max(corner_points[corner][i][1] for corner in corner_points)

        for ant in ants:
            ant_x_col = (scorer, ant, tracked_keypoint_name, 'x')
            ant_y_col = (scorer, ant, tracked_keypoint_name, 'y')

            # Retrieve the ant position if available, otherwise skip to next iteration
            ant_x = df[ant_x_col].iloc[i] if ant_x_col in df else None
            ant_y = df[ant_y_col].iloc[i] if ant_y_col in df else None

            if ant_x is not None and ant_y is not None:
                if is_inside_rectangle(ant_x, ant_y, min_x, max_x, min_y, max_y):
                    times_inside[ant] += 1

    # Compute time spent inside for each ant
    for ant in times_inside:
        times_inside[ant] /= frame_rate

    return times_inside

def count_frames_ants_in_roi_simultaneously(df, scorer, ants, corner_names, tracked_keypoint_name, frame_rate=10):
    """
    Counts the number of frames where specified ants are ever present within the ROI at the same time.

    Parameters
    ----------
    df : pandas.DataFrame
        The DataFrame containing the tracked data.
    scorer : str
        The name of the scorer used in the DataFrame.
    ants : list
        A list of ant identifiers (e.g., 'ant_1', 'ant_2') to check for simultaneous presence within the ROI.
    corner_names : list
        A list of strings representing the names of the corners to be extracted.
    tracked_keypoint_name : str
        The name of the kypoint used fr analysis
    frame_rate : int
        The frame rate of the video, by default 10 frames per second (fps).

    Returns
    -------
    int
        The number of frames where the specified ants are present within the ROI at the same time.
    """
    # Extract corner points for the entire DataFrame
    corner_points = extract_corner_points_over_frames(df, scorer, corner_names)
    overlapping_frames = 0

    for i in range(len(df)):
        min_x = min(corner_points[corner][i][0] for corner in corner_points)
        max_x = max(corner_points[corner][i][0] for corner in corner_points)
        min_y = min(corner_points[corner][i][1] for corner in corner_points)
        max_y = max(corner_points[corner][i][1] for corner in corner_points)

        inside_roi = []
        for ant in ants:
            ant_x_col = (scorer, ant, tracked_keypoint_name, 'x')
            ant_y_col = (scorer, ant, tracked_keypoint_name, 'y')

            ant_x = df[ant_x_col].iloc[i] if ant_x_col in df else None
            ant_y = df[ant_y_col].iloc[i] if ant_y_col in df else None

            # Check if the ant's position is within the ROI
            if ant_x is not None and ant_y is not None and is_inside_rectangle(ant_x, ant_y, min_x, max_x, min_y, max_y):
                inside_roi.append(ant)

        # If both ants are inside the ROI for the current frame, increment the counter
        if len(inside_roi) == len(ants):
            overlapping_frames += 1

    return overlapping_frames

def compute_total_distance(df, scorer, ants, corner_names, tracked_keypoint_name):
    """
    Computes the total distance moved by each ant within the ROI.

    Parameters
    ----------
    df : pandas.DataFrame
        The DataFrame containing the tracked data.
    scorer : str
        The name of the scorer used in the DataFrame.
    ants : list
        The list of ant identifiers (e.g., 'ant_1', 'ant_2').
    corner_names : list
        The list of corner names defining the ROI.
    tracked_keypoint_name : str
        The name of the tracked keypoint (e.g., 'ant_head').

    Returns
    -------
    dict
        A dictionary with each ant as a key and their total distance moved within the ROI as values.
    """
    # Extract corner points for the entire DataFrame
    corner_points = extract_corner_points_over_frames(df, scorer, corner_names)

    # Initialize the dictionary to store distances
    total_distances = {ant: 0 for ant in ants}

    # Loop over each frame
    for i in range(1, len(df)):
        # Determine if the ants are in the ROI for this frame
        min_x = min(corner_points[corner][i][0] for corner in corner_points)
        max_x = max(corner_points[corner][i][0] for corner in corner_points)
        min_y = min(corner_points[corner][i][1] for corner in corner_points)
        max_y = max(corner_points[corner][i][1] for corner in corner_points)

        for ant in ants:
            ant_x_col = (scorer, ant, tracked_keypoint_name, 'x')
            ant_y_col = (scorer, ant, tracked_keypoint_name, 'y')
            ant_x = df[ant_x_col].iloc[i]
            ant_y = df[ant_y_col].iloc[i]

            # Check if ant is in the ROI
            if is_inside_rectangle(ant_x, ant_y, min_x, max_x, min_y, max_y):
                # Compute the distance moved since the last frame if the ant was also in the ROI
                prev_x = df[ant_x_col].iloc[i - 1]
                prev_y = df[ant_y_col].iloc[i - 1]
                if is_inside_rectangle(prev_x, prev_y, min_x, max_x, min_y, max_y):
                    total_distances[ant] += np.sqrt((ant_x - prev_x) ** 2 + (ant_y - prev_y) ** 2)

    return total_distances

